// Regenerates the three files the manual derives from manifest.json and pages:
//
//   status.json  which pages have been written (the sidebar dims the rest)
//   _index.md    the index page listing every page with its one-line summary
//   bibliography.md  one deduplicated list of every page-level reference
//
//   node manual/tools/build.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));

/** Pull bullet references out of a page without interpreting its Markdown. */
function referencesIn(source) {
  const lines = source.split('\n');
  const references = [];
  let inside = false;
  for (const line of lines) {
    if (line === '## References') { inside = true; continue; }
    if (inside && line.startsWith('## ')) inside = false;
    if (inside && line.startsWith('- ')) references.push(line.slice(2));
  }
  return references;
}

/**
 * Prefer DOI/PubMed identity, then author-year-volume-pages.
 *
 * Pages were written over several passes, so the same paper can use a short or
 * long title. Exact-string deduplication would publish both and make the central
 * bibliography look less curated than the underlying wiki. The fallback keeps
 * genuinely different papers from the same first author and year apart.
 */
function referenceKey(reference) {
  const lower = reference.toLowerCase();
  const doi = lower.match(/doi\.org\/([^)>\s]+)/)?.[1];
  if (doi) return `doi:${doi.replace(/[.,;]+$/, '')}`;
  const pubmed = lower.match(/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)/)?.[1];
  if (pubmed) return `pmid:${pubmed}`;
  const plain = lower
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/<https?:[^>]+>/g, '')
    .replace(/[\*_`]/g, '')
    .replace(/[–—]/g, '-')
    .replace(/[^a-z0-9:/ -]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const author = plain.match(/^([a-z'-]+)/)?.[1] ?? plain.slice(0, 24);
  const year = plain.match(/\b(19|20)\d{2}\b/)?.[0] ?? '';
  const pages = plain.match(/\b\d+(?:\([^)]*\))?:[a-z]?\d+[-–][a-z]?\d+\b/)?.[0] ?? '';
  return pages ? `${author}|${year}|${pages}` : plain;
}

const sourceFiles = readdirSync(ROOT)
  .filter((f) => f.endsWith('.md') && !f.startsWith('_') && f !== 'bibliography.md');
const byKey = new Map();
for (const file of sourceFiles) {
  for (const reference of referencesIn(readFileSync(join(ROOT, file), 'utf8'))) {
    const key = referenceKey(reference);
    const previous = byKey.get(key);
    // When two pages cite the same work differently, keep the more useful form:
    // a linked DOI first, otherwise the fuller citation.
    const score = (s) => (s.includes('doi.org') ? 10000 : 0) + s.length;
    if (!previous || score(reference) > score(previous)) byKey.set(key, reference);
  }
}

const references = [...byKey.values()].sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));
const bibliography = [
  '# Bibliography',
  '',
  `> Every source cited by the current manual, collected from the page-level reference lists. ${references.length} unique entries.`,
  '',
  '---',
  '',
  'This page is generated by `manual/tools/build.mjs`. Edit the reference on the concept page where it is used; the next manual build will update this list.',
  '',
  'A citation documents the physiological or methodological claim made on its source page. Its presence here does not imply that every numerical coefficient in the model was fitted to that publication.',
  '',
];
let initial = '';
for (const reference of references) {
  const next = reference[0]?.toUpperCase() ?? '#';
  if (next !== initial) {
    initial = next;
    bibliography.push(`## ${initial}`, '');
  }
  bibliography.push(`- ${reference}`);
}
bibliography.push('', '---', '', '## See also', '', '[Home](home.md) · [Conventions](conventions.md) · [Validation](validation.md) · [Global limits](global-limits.md)', '');
// A bibliography is complete only relative to the pages currently written; the
// generated page says so explicitly rather than presenting its count as a
// systematic literature review.
bibliography.splice(-4, 0,
  '## Limits',
  '',
  'This list is complete for citations present in the current manual, not for the scientific field. Sources discussed only in repository design notes or supplied papers that are not cited by a manual page do not appear automatically.',
  '',
);
writeFileSync(join(ROOT, 'bibliography.md'), bibliography.join('\n'));

const written = readdirSync(ROOT)
  .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
  .map((f) => f.replace(/\.md$/, ''))
  .sort();

writeFileSync(join(ROOT, 'status.json'), JSON.stringify({ written }, null, 2) + '\n');

const total = manifest.sections.reduce((a, s) => a + s.pages.length, 0);
const lines = [
  '# Index',
  '',
  `> Every page in the manual, with one line each. ${written.length} of ${total} written.`,
  '',
  'This file is generated by `tools/build.mjs` from `manifest.json`. Edit the manifest, not this page.',
  '',
];

for (const section of manifest.sections) {
  lines.push(`## ${section.label}`, '');
  for (const [slug, blurb] of section.pages) {
    const mark = written.includes(slug) ? '' : ' *(not written yet)*';
    lines.push(`- [${slug.replace(/-/g, ' ')}](${slug}.md) — ${blurb}${mark}`);
  }
  lines.push('');
}

writeFileSync(join(ROOT, '_index.md'), lines.join('\n'));
console.log(`status.json: ${written.length} written of ${total}`);
console.log('_index.md: regenerated');
console.log(`bibliography.md: ${references.length} unique references`);
