// Regenerates the two files the manual derives from manifest.json:
//
//   status.json  which pages have been written (the sidebar dims the rest)
//   _index.md    the index page listing every page with its one-line summary
//
//   node manual/tools/build.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));

const written = readdirSync(ROOT)
  .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
  .map((f) => f.replace(/\.md$/, ''))
  .sort();

writeFileSync(join(ROOT, 'status.json'), JSON.stringify({ written }, null, 2) + '\n');

const total = manifest.sections.reduce((a, s) => a + s.pages.length, 0);
const lines = [
  '# Index',
  '',
  `> Every page in the manual, with one line each. ${written.length} of ${total} written.`,
  '',
  'This file is generated by `tools/build.mjs` from `manifest.json`. Edit the manifest, not this page.',
  '',
];

for (const section of manifest.sections) {
  lines.push(`## ${section.label}`, '');
  for (const [slug, blurb] of section.pages) {
    const mark = written.includes(slug) ? '' : ' *(not written yet)*';
    lines.push(`- [${slug.replace(/-/g, ' ')}](${slug}.md) — ${blurb}${mark}`);
  }
  lines.push('');
}

writeFileSync(join(ROOT, '_index.md'), lines.join('\n'));
console.log(`status.json: ${written.length} written of ${total}`);
console.log('_index.md: regenerated');
