// Generated by tests/generate-snapshots.mjs — do not edit by hand.
// Steady state after 30 s of simulated time from each preset.
export const SNAPSHOTS = {
  'healthy-spont': { co: 5.39, map: 96.0, cvp: -0.87, papMean: 16.6, paop: 9.27, pvr: 1.23 },
  'healthy-vcv': { co: 4.91, map: 93.5, cvp: 1.46, papMean: 17.0, paop: 9.72, pvr: 1.32 },
  'peep-escalation': { co: 4.29, map: 89.1, cvp: 3.92, papMean: 20.7, paop: 9.02, pvr: 2.02 },
  'septic-responder': { co: 4.13, map: 80.5, cvp: 1.76, papMean: 14.2, paop: 3.74, pvr: 1.50 },
  'swing-no-variation': { co: 6.87, map: 94.0, cvp: 1.50, papMean: 20.5, paop: 9.48, pvr: 1.27 },
  'ards-rv': { co: 3.62, map: 82.9, cvp: 4.15, papMean: 27.0, paop: 3.52, pvr: 4.33 },
  'pulmonary-embolism': { co: 3.97, map: 92.6, cvp: 5.76, papMean: 35.2, paop: 3.42, pvr: 7.79 },
  'lv-failure': { co: 3.51, map: 86.2, cvp: 4.66, papMean: 39.6, paop: 33.53, pvr: 1.74 },
  'weaning': { co: 3.60, map: 86.8, cvp: 0.58, papMean: 36.7, paop: 32.13, pvr: 1.29 },
  'obesity': { co: 4.28, map: 89.6, cvp: 3.30, papMean: 14.9, paop: 8.59, pvr: 1.28 },
  'copd': { co: 4.45, map: 88.2, cvp: 4.21, papMean: 22.7, paop: 8.73, pvr: 3.26 },
  'iah': { co: 3.44, map: 85.6, cvp: 0.79, papMean: 12.0, paop: 3.82, pvr: 1.45 },
};
