// Every knob the user can turn, in one place. The UI builds itself from this
// list, so adding a parameter here is enough to make it appear in the panel.

export const GROUPS = [
  { id: 'ventilation', label: 'Ventilation' },
  { id: 'mechanics', label: 'Respiratory mechanics' },
  { id: 'volume', label: 'Volume & vascular tone' },
  { id: 'heart', label: 'Cardiac function' },
  { id: 'pulmonary', label: 'Pulmonary circulation' },
];

export const PARAMETERS = [
  // ---------------------------------------------------------------- ventilation
  {
    id: 'mode',
    group: 'ventilation',
    label: 'Ventilatory mode',
    type: 'choice',
    options: [
      { value: 'spont', label: 'Spontaneous' },
      { value: 'vcv', label: 'Volume control' },
      { value: 'pcv', label: 'Pressure control' },
      { value: 'psv', label: 'Pressure support' },
    ],
    default: 'vcv',
    help: 'Spontaneous inspiration lowers intrathoracic pressure; every positive-pressure mode raises it. That sign change is the whole of heart–lung interaction.',
  },
  {
    id: 'rr', group: 'ventilation', label: 'Respiratory rate', unit: '/min',
    min: 6, max: 40, step: 1, default: 14,
  },
  {
    id: 'vt', group: 'ventilation', label: 'Tidal volume', unit: 'mL',
    min: 150, max: 900, step: 10, default: 450,
    appliesTo: ['vcv'],
    help: 'Tidal volume — not airway pressure — is what moves the pulmonary vasculature. Two patients with the same VT and different plateau pressures have the same PVR.',
  },
  {
    id: 'pinsp', group: 'ventilation', label: 'Inspiratory pressure', unit: 'cmH₂O above PEEP',
    min: 4, max: 40, step: 1, default: 14,
    appliesTo: ['pcv', 'psv'],
  },
  {
    id: 'peep', group: 'ventilation', label: 'PEEP', unit: 'cmH₂O',
    min: 0, max: 24, step: 1, default: 5,
    help: 'PEEP raises both end-expiratory lung volume and mean intrathoracic pressure. The first moves PVR along the J-curve; the second shifts the cardiac function curve.',
  },
  {
    id: 'ti', group: 'ventilation', label: 'Inspiratory time', unit: 's',
    min: 0.4, max: 2.5, step: 0.05, default: 1.2,
    help: 'Short expiratory time relative to the expiratory time constant traps gas and generates intrinsic PEEP.',
  },
  {
    id: 'pmus', group: 'ventilation', label: 'Inspiratory effort', unit: 'cmH₂O',
    min: 0, max: 30, step: 0.5, default: 0,
    help: 'Muscle pressure generated by the patient. Non-zero during a positive-pressure breath makes pleural pressure unpredictable — and pulse pressure variation unreliable.',
  },

  // ------------------------------------------------------------------ mechanics
  {
    id: 'position',
    group: 'mechanics',
    label: 'Body position',
    type: 'choice',
    options: [
      { value: 'supine', label: 'Supine' },
      { value: 'prone', label: 'Prone' },
    ],
    default: 'supine',
    help: 'Proning stiffens the chest wall, raises abdominal pressure and recruits dorsal lung — three changes that pull in opposite directions haemodynamically. The controls keep showing the supine mechanics; turning someone over does not change how stiff their lung is.',
  },
  {
    id: 'clung', group: 'mechanics', label: 'Lung compliance', unit: 'mL/cmH₂O',
    min: 15, max: 260, step: 5, default: 200,
    help: 'Stiff lungs (ARDS) blunt transmission of airway pressure to the pleural space, so the same PEEP costs less venous return.',
  },
  {
    id: 'ccw', group: 'mechanics', label: 'Chest wall compliance', unit: 'mL/cmH₂O',
    min: 40, max: 300, step: 5, default: 200,
    help: 'A stiff chest wall (obesity, ascites) sends more of each breath into pleural pressure, exaggerating the haemodynamic cost and pulse pressure variation.',
  },
  {
    id: 'raw', group: 'mechanics', label: 'Airway resistance', unit: 'cmH₂O/L/s',
    min: 1, max: 40, step: 0.5, default: 5,
  },
  {
    id: 'frc', group: 'mechanics', label: 'FRC', unit: 'L',
    min: 0.8, max: 4.0, step: 0.05, default: 2.2,
  },
  {
    id: 'pab0', group: 'mechanics', label: 'Baseline abdominal pressure', unit: 'cmH₂O',
    min: 0, max: 30, step: 1, default: 4,
    help: 'Sets the critical closing pressure of the IVC — the plateau of the venous return curve.',
  },
  {
    id: 'abdCoupling', group: 'mechanics', label: 'Diaphragm–abdomen coupling', unit: 'cmH₂O/L',
    min: 0, max: 12, step: 0.5, default: 4,
    help: 'Diaphragmatic descent pressurises the splanchnic reservoir, raising mean systemic filling pressure. This is why PEEP often fails to reduce the gradient for venous return.',
  },

  // --------------------------------------------------------------------- volume
  {
    id: 'stressedVolume', group: 'volume', label: 'Stressed volume', unit: 'mL',
    min: 200, max: 1800, step: 25, default: 700,
    help: 'The blood volume above the point where vessels begin to stretch. With venous compliance it sets mean systemic filling pressure — the x-intercept of the venous return curve.',
  },
  {
    id: 'csv', group: 'volume', label: 'Venous compliance', unit: 'mL/mmHg',
    min: 30, max: 200, step: 5, default: 100,
    help: 'Venoconstriction lowers compliance, raising Pmsf for the same volume. This is what a vasopressor does to the venous side.',
  },
  {
    id: 'rvr', group: 'volume', label: 'Resistance to venous return', unit: 'mmHg·s/mL',
    min: 0.02, max: 0.30, step: 0.005, default: 0.072,
    help: 'The slope of the venous return curve. Hepatic and caval compression raise it — the mechanism by which PEEP reduces venous return even with the gradient preserved.',
  },
  {
    id: 'svr', group: 'volume', label: 'Systemic vascular resistance', unit: 'mmHg·s/mL',
    min: 0.25, max: 3.0, step: 0.05, default: 1.05,
  },

  // ----------------------------------------------------------------------- heart
  { id: 'hr', group: 'heart', label: 'Heart rate', unit: '/min', min: 40, max: 170, step: 1, default: 75 },
  {
    id: 'eesLv', group: 'heart', label: 'LV contractility (Ees)', unit: 'mmHg/mL',
    min: 0.3, max: 6.0, step: 0.1, default: 3.0,
  },
  {
    id: 'eesRv', group: 'heart', label: 'RV contractility (Ees)', unit: 'mmHg/mL',
    min: 0.08, max: 1.6, step: 0.02, default: 0.58,
    help: 'The RV is a flow generator, not a pressure generator. Its low Ees is why an abrupt rise in afterload dilates it rather than being overcome.',
  },
  {
    id: 'lvStiff', group: 'heart', label: 'LV diastolic stiffness', unit: '1/mL',
    min: 0.010, max: 0.080, step: 0.002, default: 0.028,
  },
  {
    id: 'baroreflex', group: 'heart', label: 'Baroreflex gain', unit: '×',
    min: 0, max: 2, step: 0.1, default: 1.0,
    help: 'A single sympathetic outflow driving heart rate, resistance, venous tone and contractility together, with a 15 s time constant. Set to zero to see what every intervention costs a patient with no compensation — which is what this model used to assume.',
  },
  {
    id: 'baroSetPoint', group: 'heart', label: 'Baroreflex set point', unit: 'mmHg',
    min: 55, max: 110, step: 1, default: 90,
  },
  {
    id: 'pericardium', group: 'heart', label: 'Pericardial constraint', unit: '×',
    min: 0, max: 4, step: 0.1, default: 1.0,
    help: 'The four chambers share a fixed pericardial space, so filling one stiffens the others. Set to zero to abolish diastolic ventricular interdependence.',
  },
  {
    id: 'septal', group: 'heart', label: 'Septal coupling', unit: '×',
    min: 0, max: 4, step: 0.1, default: 1.0,
    help: 'Direct interventricular septal interaction. A dilating RV pushes the septum leftward and impedes LV filling — the reason fluid can worsen hypotension in RV failure.',
  },

  // ------------------------------------------------------------------- pulmonary
  {
    id: 'pvrBase', group: 'pulmonary', label: 'Baseline PVR at FRC', unit: 'mmHg·s/mL',
    min: 0.03, max: 0.60, step: 0.01, default: 0.07,
  },
  {
    id: 'hpv', group: 'pulmonary', label: 'Hypoxic vasoconstriction', unit: '×',
    min: 0, max: 3, step: 0.1, default: 1.0,
    help: 'Applied to derecruited lung below FRC. It is why lowering PEEP in RV failure can raise PVR rather than lower it.',
  },
  {
    id: 'piston', group: 'pulmonary', label: 'Pulmonary capacitance coupling', unit: 'mL/L',
    min: 0, max: 200, step: 5, default: 85,
    help: 'Lung inflation squeezes blood out of the pulmonary vessels toward the left atrium — the "piston" that drives most of the stroke volume variation seen during mechanical ventilation.',
  },
];

export const PARAM_BY_ID = new Map(PARAMETERS.map((p) => [p.id, p]));

export function defaultParams() {
  const p = {};
  for (const spec of PARAMETERS) p[spec.id] = spec.default;
  return p;
}
