// The compartment volumes, compliances and resistances are calibrated for an
// adult of about this weight. It is stated rather than buried because the
// validity condition for pulse pressure variation is expressed per kilogram.
export const REFERENCE_WEIGHT_KG = 70;

// Every knob the user can turn, in one place. The UI builds itself from this
// list, so adding a parameter here is enough to make it appear in the panel.

export const GROUPS = [
  { id: 'ventilation', label: 'Ventilation' },
  { id: 'mechanics', label: 'Respiratory mechanics' },
  { id: 'volume', label: 'Volume & vascular tone' },
  { id: 'heart', label: 'Cardiac function' },
  { id: 'pulmonary', label: 'Pulmonary circulation' },
];

export const PARAMETERS = [
  // ---------------------------------------------------------------- ventilation
  {
    id: 'mode',
    group: 'ventilation',
    label: 'Ventilatory mode',
    type: 'choice',
    options: [
      { value: 'spont', label: 'Spontaneous' },
      { value: 'vcv', label: 'Volume control' },
      { value: 'pcv', label: 'Pressure control' },
      { value: 'psv', label: 'Pressure support' },
    ],
    default: 'vcv',
    help: 'Spontaneous inspiration lowers intrathoracic pressure; positive-pressure inflation commonly raises it. Selecting volume or pressure control resets inspiratory effort to zero so the first controlled breath is passive; effort can then be reintroduced deliberately.',
  },
  {
    id: 'rr', group: 'ventilation', label: 'Respiratory rate', unit: '/min',
    min: 6, max: 40, step: 1, default: 14,
  },
  {
    id: 'vt', group: 'ventilation', label: 'Tidal volume', unit: 'mL',
    min: 150, max: 900, step: 10, default: 450,
    appliesTo: ['vcv'],
    help: 'Tidal volume moves the patient along the volume-dependent pulmonary vascular curve, but the same VT does not guarantee the same PVR or right-ventricular load. Absolute lung volume, aerated-lung strain, recruitment, flow and the alveolar waterfall also matter.',
  },
  {
    id: 'pinsp', group: 'ventilation', label: 'Inspiratory pressure', unit: 'cmH₂O above PEEP',
    min: 4, max: 40, step: 1, default: 14,
    appliesTo: ['pcv', 'psv'],
  },
  {
    id: 'peep', group: 'ventilation', label: 'PEEP', unit: 'cmH₂O',
    min: 0, max: 24, step: 1, default: 5,
    help: 'PEEP raises both end-expiratory lung volume and mean intrathoracic pressure. The first moves PVR along the J-curve; the second shifts the model RV-function curve.',
  },
  {
    id: 'ti', group: 'ventilation', label: 'Inspiratory time', unit: 's',
    min: 0.4, max: 2.5, step: 0.05, default: 1.2,
    help: 'Short expiratory time relative to the expiratory time constant traps gas and generates intrinsic PEEP.',
  },
  {
    id: 'pmus', group: 'ventilation', label: 'Inspiratory effort', unit: 'cmH₂O',
    min: 0, max: 30, step: 0.5, default: 0,
    help: 'Muscle pressure generated by the patient. Switching into volume or pressure control resets it to zero; the slider remains available if effort is then deliberately reintroduced. Non-zero effort during a positive-pressure breath makes pleural pressure unpredictable — and pulse pressure variation unreliable.',
  },

  // ------------------------------------------------------------------ mechanics
  {
    id: 'position',
    group: 'mechanics',
    label: 'Body position',
    type: 'choice',
    options: [
      { value: 'supine', label: 'Supine' },
      { value: 'prone', label: 'Prone' },
    ],
    default: 'supine',
    help: 'Proning stiffens the chest wall, raises abdominal pressure and recruits dorsal lung — three changes that pull in opposite directions haemodynamically. The controls keep showing the supine mechanics; turning someone over does not change how stiff their lung is.',
  },
  {
    id: 'clung', group: 'mechanics', label: 'Aerated-lung compliance', unit: 'mL/cmH₂O',
    min: 20, max: 420, step: 5, default: 200,
    help: 'The local volume gained per transpulmonary-pressure increment by aerated tissue while it remains away from its capacity ceiling. The live measured compliance can be lower near maximum capacity or higher while units recruit. This control changes stiffness, not maximum lung size.',
  },
  {
    id: 'lungCapacity', group: 'mechanics', label: 'Maximum lung capacity', unit: 'L',
    min: 2, max: 9, step: 0.1, default: 6,
    help: 'The volume ceiling of a completely open lung. Collapse reduces the share currently available, while recruitment restores part of it. It is independent of aerated-lung compliance and is a teaching-scale input, not an anthropometric predicted TLC.',
  },
  {
    id: 'ccw', group: 'mechanics', label: 'Chest wall compliance', unit: 'mL/cmH₂O',
    min: 40, max: 300, step: 5, default: 200,
    help: 'Local slope of the independent chest-wall recoil curve near the normal operating volume. A stiff wall sends more of each delivered volume into pleural pressure; it is distinct from an external load that shifts the whole curve.',
  },
  {
    id: 'cwLoad', group: 'mechanics', label: 'Chest wall load', unit: 'cmH₂O',
    min: -5, max: 20, step: 0.5, default: 0,
    help: 'Pressure load that shifts the relaxed chest-wall curve without changing its slope. Positive values represent mass loading or diaphragmatic/abdominal pressure transmission and can make resting pleural pressure less negative or positive.',
  },
  {
    id: 'raw', group: 'mechanics', label: 'Airway resistance', unit: 'cmH₂O/L/s',
    min: 1, max: 40, step: 0.5, default: 5,
  },
  {
    id: 'efl', group: 'mechanics', label: 'Expiratory flow limitation',
    type: 'choice',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'on', label: 'On' },
    ],
    default: 'off',
    help: 'A collapsible-airway choke during expiration: below its critical downstream pressure, a larger pressure gradient cannot increase expiratory flow. This distinguishes flow limitation from high linear resistance without adding regional lung compartments.',
  },
  {
    id: 'collapsed', group: 'mechanics', label: 'Collapsed lung', unit: 'fraction',
    min: 0, max: 0.8, step: 0.05, default: 0,
    help: 'How much of the lung is shut at rest. Resting volume is no longer something you set — it follows from how much lung is open and how compliant it is, which is what lets recruitment raise it. A lung that has lost its recoil rests high; a collapsed one rests low.',
  },
  {
    id: 'pab0', group: 'mechanics', label: 'Baseline abdominal pressure', unit: 'cmH₂O',
    min: 0, max: 30, step: 1, default: 4,
    help: 'Sets the critical closing pressure of the IVC — the plateau of the venous return curve.',
  },
  {
    id: 'abdCoupling', group: 'mechanics', label: 'Diaphragm–abdomen coupling', unit: 'cmH₂O/L',
    min: 0, max: 12, step: 0.5, default: 4,
    help: 'Diaphragmatic descent pressurises the splanchnic reservoir, raising mean systemic filling pressure. This is why PEEP often fails to reduce the gradient for venous return.',
  },

  // --------------------------------------------------------------------- volume
  {
    id: 'stressedVolume', group: 'volume', label: 'Baseline stressed volume', unit: 'mL',
    min: 200, max: 1800, step: 25, default: 700,
    help: 'The adjustable baseline volume above the systemic venous zero-pressure volume. Changing it adds or removes the same amount of blood from the venous reservoir; venous tone can then mobilise an additional amount without adding blood.',
  },
  {
    id: 'csv', group: 'volume', label: 'Venous compliance (slope)', unit: 'mL/mmHg',
    min: 30, max: 200, step: 5, default: 100,
    help: 'The change in venous volume per mmHg. It converts stressed volume into elastic filling pressure, but is independent of the venous-tone shift between unstressed and stressed volume.',
  },
  {
    id: 'rvr', group: 'volume', label: 'Resistance to venous return', unit: 'mmHg·s/mL',
    min: 0.02, max: 0.30, step: 0.005, default: 0.072,
    help: 'The slope of the venous return curve. Hepatic and caval compression raise it — the mechanism by which PEEP reduces venous return even with the gradient preserved.',
  },
  {
    id: 'svr', group: 'volume', label: 'Systemic vascular resistance', unit: 'mmHg·s/mL',
    min: 0.25, max: 3.0, step: 0.05, default: 1.05,
  },

  // ----------------------------------------------------------------------- heart
  {
    id: 'hr', group: 'heart', label: 'Baseline heart rate', unit: '/min',
    min: 40, max: 170, step: 1, default: 75,
    help: 'The intrinsic rate selected for the patient. When the baroreflex is on, the effective rate used by the circulation also includes the reflex contribution shown in the Heart rate tile.',
  },
  {
    id: 'eesLv', group: 'heart', label: 'LV contractility (Ees)', unit: 'mmHg/mL',
    min: 0.3, max: 6.0, step: 0.1, default: 3.0,
    help: 'Peak active slope of the LV end-systolic pressure–volume relation. The ventricular activation waveform is normalised to reach this selected value; ejection fraction remains load-dependent.',
  },
  {
    id: 'eesRv', group: 'heart', label: 'RV contractility (Ees)', unit: 'mmHg/mL',
    min: 0.08, max: 1.6, step: 0.02, default: 0.58,
    help: 'Peak active slope of the RV end-systolic pressure–volume relation. The RV is a flow generator, not a pressure generator; its low Ees is why an abrupt rise in afterload dilates it rather than being overcome.',
  },
  {
    id: 'lvStiff', group: 'heart', label: 'LV diastolic stiffness', unit: '1/mL',
    min: 0.010, max: 0.080, step: 0.002, default: 0.028,
  },
  {
    id: 'baroreflexEnabled', group: 'heart', label: 'Baroreflex',
    type: 'choice',
    options: [
      { value: false, label: 'Off' },
      { value: true, label: 'On' },
    ],
    default: false,
    help: 'Off exposes the uncompensated mechanical heart–lung interaction. On adds one slow aggregate pressure-defence response that changes effective heart rate, systemic resistance, venous tone and contractility together.',
  },
  {
    id: 'baroreflex', group: 'heart', label: 'Baroreflex sensitivity', unit: '×',
    min: 0, max: 2, step: 0.1, default: 1.0,
    requires: { id: 'baroreflexEnabled', value: true },
    help: 'Gain of the bounded pressure-error response when the baroreflex is on. It uses one 15 s time constant and is not a beat-to-beat human baroreflex model. Changing the gain does not change the maximum response.',
  },
  {
    id: 'baroSetPoint', group: 'heart', label: 'Baroreflex set point', unit: 'mmHg',
    min: 55, max: 110, step: 1, default: 90,
    requires: { id: 'baroreflexEnabled', value: true },
  },
  {
    id: 'pericardium', group: 'heart', label: 'Pericardial constraint', unit: '×',
    min: 0, max: 4, step: 0.1, default: 1.0,
    help: 'Gain on the pressure generated when the four chambers outgrow the space available inside the pericardium. Set to zero to abolish this route of diastolic ventricular interdependence.',
  },
  {
    id: 'pericardialCapacity', group: 'heart', label: 'Pericardial capacity', unit: 'mL',
    min: 100, max: 600, step: 10, default: 430,
    help: 'Aggregate four-chamber volume accommodated before pericardial pressure rises steeply. Reducing it represents loss of available space, as with a pressurised effusion; it is an internal model capacity, not a measured effusion volume.',
  },
  {
    id: 'septal', group: 'heart', label: 'Septal coupling', unit: '×',
    min: 0, max: 4, step: 0.1, default: 1.0,
    help: 'Direct interventricular septal interaction. A dilating RV pushes the septum leftward and impedes LV filling — the reason fluid can worsen hypotension in RV failure.',
  },

  // ------------------------------------------------------------------- pulmonary
  {
    id: 'pvrBase', group: 'pulmonary', label: 'Open-lung PVR at FRC', unit: 'mmHg·s/mL',
    min: 0.03, max: 0.60, step: 0.01, default: 0.07,
    help: 'The resistance coefficient of a fully open lung at its resting volume. Collapse and hypoxic vasoconstriction then redistribute flow between open and derecruited vascular pathways.',
  },
  {
    id: 'riRatio', group: 'mechanics', label: 'Recruitment-to-inflation ratio', unit: 'R/I',
    min: 0, max: 2, step: 0.05, default: 0.5,
    help: 'Supine bedside R/I for a passive PEEP 5 to 15 cmH₂O manoeuvre: compliance of recruited volume divided by respiratory-system compliance at low PEEP. Values below 0.5 describe lower recruitment relative to inflation; 0.5 is a cohort-derived teaching threshold, not an outcome-proven treatment cutoff. Collapse remains a separate input: if too little lung is closed to realise the requested R/I, the model stops at the available lung and flags the shortfall. Proning may change the achieved readout by shifting opening pressures.',
  },
  {
    id: 'pOpen', group: 'mechanics', label: 'Opening pressure', unit: 'cmH₂O',
    min: 5, max: 40, step: 1, default: 20,
    help: 'Recruitment occurs over a range, not at one pressure. This is the centre of that opening range for the collapsed but recruitable part of the lung: below it fewer than half of those units are open, above it more than half are. It is a transpulmonary pressure, not the airway-opening pressure used to correct a bedside R/I manoeuvre.',
  },
  {
    id: 'hysteresis', group: 'mechanics', label: 'Recruitment hysteresis',
    type: 'choice',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'on', label: 'On' },
    ],
    default: 'off',
    help: 'Off, units open and close at the same pressure, so how much lung is open follows the pressure of the moment and nothing you do to it lasts. On, they close at a lower pressure than they opened at, so how much is open becomes a state with a history — which is what makes a recruitment manoeuvre buy anything, and what makes a decremental PEEP trial land somewhere different from an incremental one.',
  },
  {
    id: 'pClose', group: 'mechanics', label: 'Closing pressure', unit: 'cmH₂O',
    min: 2, max: 40, step: 1, default: 12,
    requires: { id: 'hysteresis', value: 'on' },
    help: 'Derecruitment also occurs over a range. This is the centre of the closing range for previously recruited diseased units: half remain open here during falling pressure. Already-aerated lung does not acquire this memory. It only has an effect with hysteresis on and below the opening pressure; setting the two pressures equal switches the memory off.',
  },
  {
    id: 'hpv', group: 'pulmonary', label: 'Hypoxic vasoconstriction', unit: '×',
    min: 0, max: 3, step: 0.1, default: 1.0,
    help: 'Raises resistance only in the vascular pathway of derecruited units. It can redirect flow toward open lung, but severe collapse still reduces the vascular bed available to the right ventricle.',
  },
  {
    id: 'piston', group: 'pulmonary', label: 'Pulmonary capacitance coupling', unit: 'mL/L',
    min: 0, max: 200, step: 5, default: 85,
    help: 'Sets how strongly lung inflation transiently displaces blood from the pulmonary vascular reservoir toward the left atrium. This "piston" is one immediate contributor to LV filling and stroke-volume variation; changes in RV preload and afterload, reaching the left heart after pulmonary transit, may dominate in other phenotypes.',
  },
];

export const PARAM_BY_ID = new Map(PARAMETERS.map((p) => [p.id, p]));

export function defaultParams() {
  const p = {};
  for (const spec of PARAMETERS) p[spec.id] = spec.default;
  return p;
}
